import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { TRPCReactProvider } from "@/trpc/react";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedOut,
  SignedIn,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <TRPCReactProvider>
        <ReactQueryDevtools initialIsOpen={false} />

        <html lang="en" className={`${geist.variable}`}>
          <body className="bg-primaryBg h-screen text-white">
            <SignedIn>{children}</SignedIn>

            <SignedOut>
              <div className="flex h-[70%] items-center justify-center gap-4">
                <SignInButton forceRedirectUrl={"/home"}>
                  <Button className="rounded-lg border border-2 border-black p-8 text-3xl shadow-[4px_4px_0_#8A4A2F] hover:bg-[#8E3B15]">
                    Sign In
                  </Button>
                </SignInButton>
                <SignUpButton forceRedirectUrl={"/home"}>
                  <Button className="py rounded-lg border border-2 border-black p-8 text-3xl shadow-[4px_4px_0_#8A4A2F] hover:bg-[#8E3B15]">
                    Sign up
                  </Button>
                </SignUpButton>
              </div>
            </SignedOut>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
