import "@/styles/globals.css";
import "@digabi/mathquill/build/mathquill.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { dark } from "@clerk/themes";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <TRPCReactProvider>
        <ReactQueryDevtools initialIsOpen={false} />

        <html lang="en" className={`${geist.variable}`}>
          <body className="bg-primaryBg h-screen text-white">{children}</body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
